development:
  adapter: postgresql
  database: natesite
  username:
  host: localhost

test:
  adapter: postgresql
  database: natesite
  username:
  host: localhost

production:
  adapter: postgresql
  database: natesite
  username:
